
BLENDER="C:\Program Files\Blender Foundation\Blender 3.6\blender.exe"
DIST=../dist

all : \
    $(DIST)/simple.scene \
    $(DIST)/simple.pnct \

$(DIST)/simple.scene : simple.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "simple.blend:Main" "$(DIST)/simple.scene"

$(DIST)/simple.pnct : simple.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "simple.blend:Main" "$(DIST)/simple.pnct" 
